FROM debian:11@sha256:6f519a81440354a85eb592c5f32109ab80605f6b892455983a6f618bf87fabe9

RUN sed -i \
        -e 's/^deb http:\/\/deb.debian.org/# deb http:\/\/deb.debian.org/' \
        -e 's/^# deb http:\/\/snapshot.debian.org/deb http:\/\/snapshot.debian.org/' \
        /etc/apt/sources.list \
    && apt-get -o Acquire::Check-Valid-Until=false update \
    && apt-get install -y --no-install-recommends btrfs-progs e2fsprogs git python3 util-linux \
    && rm -rf /var/lib/apt/lists/* \
    && useradd --create-home --uid 1000 thinws
